# Jekyll Resume Theme

# Site settings
title: Jekyll Resume
email: email@domain.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "http://zile zhang.co.uk/jekyll-resume"
name: Zile Zhang
job: student
location: guangzhou, China
languages: chinese、english、cantonese
github_username: zile_NM
email_address: 1394440262@qq.com

# Build settings
markdown: kramdown
